<?php
$messages = [
    'it' => [
        'lang_name' => '🇮🇹 Italiano',
        'lang_404' => 'Questa lingua non è disponibile',
        'choose_lang' => '🌐 <b>Scegli la tua lingua:</b>',
        'lang_chosen' => '🇮🇹 <b>Lingua impostata a italiano</b>',
        'next' => '➡️ Avanti',
        'manage_bots' => '🤖 Gestisci Bot',
        'set_webhook' => '🔗 Imposta Wb',
        'info_webhook' => 'ℹ️ Informazioni Wb',
        'delete_webhook' => '🗑 Rimuovi Wb',
        'delete_updates' => '♻️ Rimuovi update',
        'refresh' => '♻️ Ricarica',
        'settings' => '⚙️ Impostazioni',
        'add_bot' => '➕ Aggiungi bot',
        'delete' => '📛 Rimuovi Bot',
        'go_back' => '🔙 Torna Indietro',
        'change_lang' => '🌐 Cambia Lingua',
        'settings_text' => '⚙ <b>Impostazioni</b> ⚙' . "\n\n" . 'Quì puoi gestire le informazioni riguardanti il tuo account.',
        'bots_text' => '🤖 <b>Gestisci Bot</b> 🤖' . "\n\n" . 'Quì potrai aggiungere alcuni bot in modo da rendere più semplici e veloci le azioni su di essi, utilizza il pulsante aggiungi bot per aggiungere un bot o clicca sull\'username di un bot per gestirlo.',
        'bot_panel' => '🤖 <b>Gestione Bot</b> 🤖' . "\n\n" . '➥ <b>Info Bot:</b>'. "\n👤 <b>Nome:</b> &name\n🆔 <b>ID Bot:</b> <code>&id</code>\n📄 <b>Username:</b> @&username\nℹ️ <b>Token:</b> <code>&token</code>\n🔗 <b>Endpoint:</b> https://api.telegram.org/bot&token/method\n\n<i>Scegli un'opzione per questo bot</i>",
        'wbinfo' => 'ℹ️ <b>Informazioni Webhook</b> ℹ️' . "\n\n" . '➥ <b>Info Bot:</b>'. "\n👤 <b>Nome:</b> &name\n🆔 <b>ID Bot:</b> <code>&id</code>\n📄 <b>Username:</b> @&username" .  "\n\n" . '➥ <b>Info Webhook:</b>'. "\n🔗 <b>URL:</b> &url\n♻️ <b>Pending Update:</b> <code>&updates</code>\n💣 <b>Limite Webhook:</b> &limit\n🚫 <b>Ultimo errore:</b> &error (&date)\n<a href='https://api.telegram.org/bot&token/getWebhookInfo'>Vedi Altro</a>",
        'webhookinfo_text' => 'ℹ️ <b>Informazioni Webhook</b> ℹ️' . "\n\n" . 'Per controllare le informazioni del WebHook puoi:'.PHP_EOL.'➥ Inviare il token del bot ora'.PHP_EOL.'➥ Se ne hai aggiunti, puoi scegliere uno dei bot sottostanti'.PHP_EOL.'➥ Usare in qualunque momento il comando <code>/infowb TOKEN</code>',
        'deletewb_text' => '🗑 <b>Rimuovi Webhook</b> 🗑' . "\n\n" . 'Per rimuovere il webhook di un bot puoi:'.PHP_EOL.'➥ Inviare il token del bot ora'.PHP_EOL.'➥ Se ne hai aggiunti, puoi scegliere uno dei bot sottostanti'.PHP_EOL.'➥ Usare in qualunque momento il comando <code>/delwb TOKEN</code>',
        'deleteup_text' => '♻️ <b>Rimuovi Update</b> ♻️' . "\n\n" . 'Per rimuovere gli update in sospeso nel tuo bot puoi:'.PHP_EOL.'➥ Inviare il token del bot ora'.PHP_EOL.'➥ Se ne hai aggiunti, puoi scegliere uno dei bot sottostanti'.PHP_EOL.'➥ Usare in qualunque momento il comando <code>/delup TOKEN</code>',
        'setwb_text' => '🔗 <b>Imposta Webhook</b> 🔗️' . "\n\n" . 'Per impostare il WebHook puoi:'.PHP_EOL.'➥ Inviare il token del bot ora'.PHP_EOL.'➥ Se ne hai aggiunti, puoi scegliere uno dei bot sottostanti',
        'add_bot_text' => '➕ <b>Add Bot</b> ➕' . "\n\n" . 'Invia il token del bot e lo aggiungerò alla lista.',
        'start' => '<a href="https://www.silveros.it/img/devtoolsbanner.png">⚙</a>️ <b>DevToolsForBot</b> ⚙' . PHP_EOL . PHP_EOL. 'ℹ️ Con questo bot puoi:' . PHP_EOL . '➥ Impostare e gestire i tuoi bot facilmlente'. PHP_EOL . '➥ Visualizzare le informazioni del webhook' . PHP_EOL . '➥ Rimuovere update in sospeso dal tuo bot' . "\n\n" . '⚠️ Utilizzando il bot confermi di aver <a href="https://telegra.ph/Informativa-riguardo-ai-rischi-di-DevToolsForBot-06-03">letto e capito l\'informativa sui richi</a>' . PHP_EOL . PHP_EOL . '⚙️ <b>Sviluppato da @SilverOSp</b>',
        'bot_added' => '✅ <b>Fatto</b> ✅'. PHP_EOL . PHP_EOL. 'Il bot &username è stato aggiunto alla tua lista',
        'send_url' => '✅ <b>Fatto</b> ✅'. PHP_EOL . PHP_EOL. 'Il token è valido, ora <b>invia il link del Webhook</b>, ricorda che deve iniziare necessariamente con https://',
        'wb_set' => '✅ <b>Fatto</b> ✅'. PHP_EOL . PHP_EOL. 'Il webhook è stato impostato con successo.',
        'wb_not_set' =>  '❌ <b>Errore</b> ❌' . PHP_EOL . PHP_EOL. 'Il webhook non è stato impostato, le API hanno fornito questo errore: &error',
        'e_token_not_valid' => '❌ <b>Errore</b> ❌' . PHP_EOL . PHP_EOL. 'Il token che hai inserito non è valido',
        'e_token_expired' => '❌ <b>Errore</b> ❌' . PHP_EOL . PHP_EOL. 'Il token che del bot è cambiato, ho rimosso il bot dalla lista',
        'e_infowb' => '❌ <b>Errore</b> ❌' . PHP_EOL . PHP_EOL. 'La sintassi non è valida, utilizza il comando' . PHP_EOL . '<code>/infowb token</code>',
        'e_delwb' => '❌ <b>Errore</b> ❌' . PHP_EOL . PHP_EOL. 'La sintassi non è valida, utilizza il comando' . PHP_EOL . '<code>/delwb token</code>',
        'e_delup' => '❌ <b>Errore</b> ❌' . PHP_EOL . PHP_EOL. 'La sintassi non è valida, utilizza il comando' . PHP_EOL . '<code>/delup token</code>',
        'delete_confirm' => '📛 <b>Rimuovi Bot</b> 📛' . "\n\n" . 'Sei sicuro di voler eliminare &username da DevToolsForBot? Tutte le informazioni riguardo ad esso verranno eliminate.',
        'deletewb_confirm' => '🗑 <b>Delete Webhook</b> 🗑' . "\n\n" . 'Sei sicuro di voler eliminare il webhook di &username?',
        'bot_deleted' => '✅ <b>Fatto</b> ✅'. PHP_EOL . PHP_EOL. 'Il bot è stato rimosso',
        'updates_deleted' => '✅ <b>Fatto</b> ✅'. PHP_EOL . PHP_EOL. 'Gli update in sospeso sono stati rimossi',
        'wb_deleted' => '✅ <b>Fatto</b> ✅'. PHP_EOL . PHP_EOL. 'Il webhook è stato rimosso',
        '404_page' => 'Pagina non disponibile.',

    ],
    'en' => [
        'lang_name' => '🇬🇧 English',
        'lang_404' => 'This language is not available',
        'choose_lang' => '🌐 <b>Select your language:</b>',
        'lang_chosen' => '🇬🇧 <b>Language set to English</b>',
        'next' => '➡️ Next',
        'manage_bots' => '🤖 Manage Bots',
        'set_webhook' => '🔗 Set Wb',
        'info_webhook' => 'ℹ️ Wb Information',
        'delete_webhook' => '🗑 Delete Wb',
        'delete_updates' => '♻️ Remove updates',
        'refresh' => '♻️ Refresh',
        'settings' => '⚙️ Settings',
        'add_bot' => '➕ Add Bot',
        'delete' => '📛 Remove Bot',
        'go_back' => '🔙 Go Back',
        'change_lang' => '🌐 Change Language',
        'settings_text' => '⚙ <b>Settings</b> ⚙' . "\n\n" . 'Here you can manage your account settings.',
        'bots_text' => '🤖 <b>Manage Bots</b> 🤖' . "\n\n" . 'Here you can add bots so that you don\'t have to send their token every time, use the Add Bot button to add a bot or click on the bot\'s username to manage it.',
        'bot_panel' => '🤖 <b>Manage Bot</b> 🤖' . "\n\n" . '➥ <b>Bot information:</b>'. "\n👤 <b>Name:</b> &name\n🆔 <b>Bot ID:</b> <code>&id</code>\n📄 <b>Username:</b> @&username\nℹ️ <b>Token:</b> <code>&token</code>\n🔗 <b>Endpoint:</b> https://api.telegram.org/bot&token/method\n\n<i>Choose an option:</i>",
        'wbinfo' => 'ℹ️ <b>Webhook Information</b> ℹ️' . "\n\n" . '➥ <b>Bot information:</b>'. "\n👤 <b>Name:</b> &name\n🆔 <b>Bot ID:</b> <code>&id</code>\n📄 <b>Username:</b> @&username" .  "\n\n" . '➥ <b>Webhook information:</b>'. "\n🔗 <b>URL:</b> &url\n♻️ <b>Pending Updates:</b> <code>&updates</code>\n💣 <b>Webhook Limit:</b> &limit\n🚫 <b>Last Error:</b> &error (&date)\n<a href='https://api.telegram.org/bot&token/getWebhookInfo'>See More</a>",
        'webhookinfo_text' => 'ℹ️ <b>Webhook Information</b> ℹ️' . "\n\n" . 'To see webhook information you can:'.PHP_EOL.'➥ Send the bot token now'.PHP_EOL.'➥ You can choose one of the bot you added'.PHP_EOL.'➥ Use the command <code>/infowb TOKEN</code>',
        'deletewb_text' => '🗑 <b>Remove Webhook</b> 🗑' . "\n\n" . 'To remove the webhook you can:'.PHP_EOL.'➥ Send the bot token now'.PHP_EOL.'➥ You can choose one of the bot you added'.PHP_EOL.'➥ Use the command <code>/delwb TOKEN</code>',
        'deleteup_text' => '♻️ <b>Remove Updates</b> ♻️' . "\n\n" . 'To remove every pending update you can:'.PHP_EOL.'➥ Send the bot token now'.PHP_EOL.'➥ You can choose one of the bot you added'.PHP_EOL.'➥ Use the command <code>/delup TOKEN</code>',
        'setwb_text' => '🔗 <b>Set Webhook</b> 🔗️' . "\n\n" . 'To set the webhook you can:'.PHP_EOL.'➥ Send the bot token now'.PHP_EOL.'➥ You can choose one of the bot you added',
        'add_bot_text' => '➕ <b>Add Bot</b> ➕' . "\n\n" . 'Send me the bot token and I will add it to the list.',
        'start' => '<a href="https://www.silveros.it/img/devtoolsbanner.png">⚙</a>️ <b>DevToolsForBot</b> ⚙' . PHP_EOL . PHP_EOL. 'ℹ️ With this bot you can:' . PHP_EOL . '➥ Easly manage your bots'. PHP_EOL . '➥ See webhook information' . PHP_EOL . '➥ Delete updates from your bots' . "\n\n" . '⚠️ Using this bot you confirm that you have <a href="https://telegra.ph/Information-on-the-risks-using-DevToolsForBot-06-03">read and understood the information on the risks</a>' . PHP_EOL . PHP_EOL . '⚙️ <b>Developed by @SilverOSpEN</b>',
        'bot_added' => '✅ <b>Done</b> ✅'. PHP_EOL . PHP_EOL. '&username has been added to the list',
        'send_url' => '✅ <b>Done</b> ✅'. PHP_EOL . PHP_EOL. 'The token is valid, now <b>send the Webhook link</b>, remember that it must start with https://',
        'wb_set' => '✅ <b>Done</b> ✅'. PHP_EOL . PHP_EOL. 'Webhook set successfully.',
        'wb_not_set' =>  '❌ <b>Error</b> ❌' . PHP_EOL . PHP_EOL. 'The Webhook was not set, error: &error',
        'e_token_not_valid' => '❌ <b>Error</b> ❌' . PHP_EOL . PHP_EOL. 'This token is not valid',
        'e_token_expired' => '❌ <b>Error</b> ❌' . PHP_EOL . PHP_EOL. 'Bot\'s token is not valid anymore, i have removed it from the list',
        'e_infowb' => '❌ <b>Error</b> ❌' . PHP_EOL . PHP_EOL. 'Wrong syntax, use' . PHP_EOL . '<code>/infowb token</code>',
        'e_delwb' => '❌ <b>Error</b> ❌' . PHP_EOL . PHP_EOL. 'Wrong syntax, use' . PHP_EOL . '<code>/delwb token</code>',
        'e_delup' => '❌ <b>Error</b> ❌' . PHP_EOL . PHP_EOL. 'Wrong syntax, use' . PHP_EOL . '<code>/delup token</code>',
        'delete_confirm' => '📛 <b>Remove Bot</b> 📛' . "\n\n" . 'Are you sure that you want to remove &username from DevToolsForBot? Every information about it will be deleted.',
        'deletewb_confirm' => '🗑 <b>Delete Webhook</b> 🗑' . "\n\n" . 'Are you sure that you want to delete &username\' webhook?',
        'bot_deleted' => '✅ <b>Done</b> ✅'. PHP_EOL . PHP_EOL. 'Bot removed',
        'updates_deleted' => '✅ <b>Done</b> ✅'. PHP_EOL . PHP_EOL. 'Pending updates removed',
        'wb_deleted' => '✅ <b>Done</b> ✅'. PHP_EOL . PHP_EOL. 'Webhook removed',
        '404_page' => 'Page not available.',
    ],
    'na' => [
        'lang_name' => '💰 Napoletano',
        'lang_404' => 'Sta lingua nun c\'è chiù',
        'choose_lang' => '🌐 <b>Pigl a ling toia:</b>',
        'lang_chosen' => '💰 <b>Ling mess a Napuletan</b>',
        'next' => '➡️ Avanti',
        'manage_bots' => '🤖 Gestisc Bot',
        'set_webhook' => '🔗 Imposta Wb',
        'info_webhook' => 'ℹ️ Informazion Wb',
        'delete_webhook' => '🗑 Togl Wb',
        'delete_updates' => '♻️ Togl update',
        'refresh' => '♻️ Ricarica',
        'settings' => '⚙️ Preferenz',
        'add_bot' => '➕ Aggiung Bot',
        'delete' => '📛 TOgl Bot',
        'go_back' => '🔙 Vai Aretr',
        'change_lang' => '🌐 Pigl n\'ata ling',
        'settings_text' => '⚙ <b>Preferenz</b> ⚙' . "\n\n" . 'Ca\' poi scegl chill che preferisc.',
        'bots_text' => '🤖 <b>Gestisc Bot</b> 🤖' . "\n\n" . 'Ca\' poi ficcà i bot accussì se sì tropp pigr pe\' mannà u token ru bot ogni vota ciu ficc io',
        'bot_panel' => '🤖 <b>Gestion Bot</b> 🤖' . "\n\n" . '➥ <b>Fedina penale:</b>'. "\n👤 <b>Nomm:</b> &name\n🆔 <b>Targa:</b> <code>&id</code>\n📄 <b>Username:</b> @&username\nℹ️ <b>Token:</b> <code>&token</code>\n🔗 <b>Endpoint:</b> https://api.telegram.org/bot&token/method\n\n<i>Scegli un'opzione per questo bot</i>",
        'wbinfo' => 'ℹ️ <b>Informazioni Webhook</b> ℹ️' . "\n\n" . '➥ <b>Info Bot:</b>'. "\n👤 <b>Nomm:</b> &name\n🆔 <b>Targa:</b> <code>&id</code>\n📄 <b>Username:</b> @&username" .  "\n\n" . '➥ <b>Collegament ca\' camorr:</b>'. "\n🔗 <b>URL:</b> &url\n♻️ <b>Debbiti pe u pizz:</b> <code>&updates</code>\n💣 <b>Quann te sparan m'occ:</b> &limit\n🚫 <b>Ultem avvertiment:</b> &error (&date)\n<a href='https://api.telegram.org/bot&token/getWebhookInfo'>Altr</a>",
        'webhookinfo_text' => 'ℹ️ <b>Informazion Webhook</b> ℹ️' . "\n\n" . 'Pe\' controllà le informazion ru webhook poi:'.PHP_EOL.'➥ Mandà u token mo'.PHP_EOL.'➥ Piglià nu bot sott'.PHP_EOL.'➥ Usà u cumand quann te par <code>/infowb TOKEN</code>',
        'deletewb_text' => '🗑 <b>Togl u Webhook</b> 🗑' . "\n\n" . 'Pe\' togl u webhook poi:'.PHP_EOL.'➥ Mandà u token mo'.PHP_EOL.'➥ Piglià nu bot sott'.PHP_EOL.'➥ Usà u cumand quann te par <code>/delwb TOKEN</code>',
        'deleteup_text' => '♻️ <b>Togl Update</b> ♻️' . "\n\n" . 'Pe\' togl i debbiti co a camorr poi:'.PHP_EOL.'➥ Mandà u token mo'.PHP_EOL.'➥ Pagarl'.PHP_EOL.'➥ Piglià nu bot sott'.PHP_EOL.'➥ Usà u cumand quann te par <code>/delup TOKEN</code>',
        'setwb_text' => '🔗 <b>Imposta Webhook</b> 🔗️' . "\n\n" . 'Pe\' impostà u webhook poi:'.PHP_EOL.'➥ Mandà u token mo'.PHP_EOL.'➥ Piglià nu bot sott',
        'add_bot_text' => '➕ <b>Ficc bot</b> ➕' . "\n\n" . 'Mann u token ru\' bot che u ficc rinn a list.',
        'start' => '<a href="https://www.silveros.it/img/devtoolsbanner.png">⚙</a>️ <b>DevToolsForBot</b> ⚙' . PHP_EOL . PHP_EOL. 'ℹ️ Cu\' stu bot poi:' . PHP_EOL . '➥ Gestì i bot toi'. PHP_EOL . '➥ Guardà le informazion ru Webhook' . PHP_EOL . '➥ Togl i debbit co a camorr' . "\n\n" . '⚠️ Utilizzando il bot confermi di aver <a href="https://telegra.ph/Informativa-riguardo-ai-rischi-di-DevToolsForBot-06-03">letto e capito l\'informativa sui richi</a>' . PHP_EOL . PHP_EOL . '⚙️ <b>Sviluppat da @SilverOSp</b>',
        'bot_added' => '✅ <b>Fatt</b> ✅'. PHP_EOL . PHP_EOL. 'U bot &username è stato ficcat rinn a list',
        'send_url' => '✅ <b>Fatt</b> ✅'. PHP_EOL . PHP_EOL. 'U tekn è giusto, mo <b>mand u link ru Webhook</b>, ricord che adda inizà co\' https://',
        'wb_set' => '✅ <b>Fatt</b> ✅'. PHP_EOL . PHP_EOL. 'Webhook ficcat con success',
        'wb_not_set' =>  '❌ <b>Error</b> ❌' . PHP_EOL . PHP_EOL. 'Webhook non ficcat pecchè: &error',
        'e_token_not_valid' => '❌ <b>Error</b> ❌' . PHP_EOL . PHP_EOL. 'U token è sbagliat',
        'e_token_expired' => '❌ <b>Error</b> ❌' . PHP_EOL . PHP_EOL. 'U token è cambbiat, ho sparat stu bot',
        'e_infowb' => '❌ <b>Error</b> ❌' . PHP_EOL . PHP_EOL. 'Hai sbagliat a sintass, a usà' . PHP_EOL . '<code>/infowb token</code>',
        'e_delwb' => '❌ <b>Error</b> ❌' . PHP_EOL . PHP_EOL. 'Hai sbagliat a sintass, a usà' . PHP_EOL . '<code>/delwb token</code>',
        'e_delup' => '❌ <b>Error</b> ❌' . PHP_EOL . PHP_EOL. 'Hai sbagliat a sintass, a usà' . PHP_EOL . '<code>/delup token</code>',
        'delete_confirm' => '📛 <b>Togl Bot</b> 📛' . "\n\n" . 'Sì propr sicur che vu togl &username da DevToolsForBot? Toglieò tutt e prov.',
        'deletewb_confirm' => '🗑 <b>Togl u Webhook</b> 🗑' . "\n\n" . 'Si propr sicur che vu togl u webhook de &username?',
        'bot_deleted' => '✅ <b>Fatt</b> ✅'. PHP_EOL . PHP_EOL. 'Agg sparat a u bot',
        'updates_deleted' => '✅ <b>Fatt</b> ✅'. PHP_EOL . PHP_EOL. 'T\'ho tolt tutti i debbit',
        'wb_deleted' => '✅ <b>Fatt</b> ✅'. PHP_EOL . PHP_EOL. 'Ho tolt u webhook',
        '404_page' => 'Te si pers pe napule.',

    ],

];